name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.5
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.0.7
          elixir-version: 1.9.1
      - name: Install Dependencies
        run: mix deps.get
      - name: Setup Database
        run: mix ecto.setup
      - name : Run Tests
        run: mix test
